name: Issue notifications

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  telegram:
    name: Telegram
    uses: ./.github/workflows/subflow_send_telegram_notification.yaml
    with:
      notification_type: issue
    secrets:
      TELEGRAM_CHAT_ID: |
        ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
        ${{ secrets.TELEGRAM_K8S_OPERATOR_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
